#打印sql日志信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#eureka:
#  instance:
#    #    给注册到eureka中的URL起一个别名
#    instance-id: payment8001
  #    #    访问路径可以显示IP地址，放在修改后的名称上，页面左下角会出现对应的URL
  #    prefer-ip-address: true
  #    #    eureka客户端向服务端发送心跳的时间间隔，单位为妙(默认为30秒)
  #    lease-renewal-interval-in-seconds: 1
  #    #   eureka服务端在收到最后一次等待时间的上限，单位为妙(默认是90秒)，超时将剔除服务
  #    lease-expiration-duration-in-seconds: 2
#  client:
    #表示是否将自己注册进EurekaServer默认为true。
#    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    service-url:
      #单机版
#            defaultZone: http://localhost:7001/eureka
      #集群
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/